@c FILE     Main.texi
@c PACKAGE  ExpressionTree
@c AUTHOR   Edward S. Blurock
@c 
@c CONTENT
@c   Texinfo documentation for CoreObjects library package "ExpressionTree".
@c
@c REFERENCES
@c
@c COPYRIGHT (C) CoreObjects Library

@node     ExpressionTree Package
@section  The "ExpressionTree" Package
@cindex   package, ExpressionTree
@cindex   ExpressionTree package
@cindex   extr namespace
@cindex   namespaces, extr

@table @strong
@item Package name
@code{ExpressionTree}

@item Namespace name
@code{extr}

@item Header files
@file{ExpressionTree.hh}, @file{ExpressionTreeType.hh}
@end table


@include ExpressionTree/Overview.texi

@include ExpressionTree/Classes.texi
