# FILE     Makefile
# PACKAGE  LineGraph
# AUTHOR   Edward S. Blurock
#
# CONTENT
#   Makefile for example programs of the "LineGraph" package.
#
# COPYRIGHT (C)  1997 Basis Library

#V PackageRoot . . . . . . . . . . . . . . The root directory of this package.
PackageRoot:=$(shell cd ../..; pwd)


#I
include ../../etc/Basis/MakeDef

LDLIBS+=\
  -lLineGraph


#V
ALL=


#F Targets.

all: $(ALL)


cleaner::
	$(RM) $(ALL)
