# FILE     Makefile
# PACKAGE  EquivalentClasses
# AUTHOR   Edward S. Blurock
#
# CONTENT
#   Makefile for example programs of the "EquivalentClasses" package.
#
# COPYRIGHT (C)  1997 CoreObjects Library

#V PackageRoot . . . . . . . . . . . . . . The root directory of this package.
PackageRoot:=$(shell cd ../..; pwd)


#I
include ../../etc/CoreObjects/MakeDef

LDLIBS+=\
  -lEquivalentClasses


#V
ALL=


#F Targets.

all: $(ALL)


cleaner::
	$(RM) $(ALL)
