# FILE     Makefile
# PACKAGE  EvaluationTree
# AUTHOR   Edward S. Blurock
#
# CONTENT
#   Makefile for example programs of the "EvaluationTree" package.
#
# COPYRIGHT (C)  1997 CoreObjects Library

#V PackageRoot . . . . . . . . . . . . . . The root directory of this package.
PackageRoot:=$(shell cd ../..; pwd)


#I
include ../../etc/CoreObjects/MakeDef

LDLIBS+=\
  -lEvaluationTree


#V
ALL=


#F Targets.

all: $(ALL)


cleaner::
	$(RM) $(ALL)
